import { NutrientType } from './types/nutrient.type';
import { SexEnum } from './types/sex.type';

export class NutrientMetaData {
    nutrient: NutrientType;
    displayName: string;
    aliases: string[];
    defaultUnit: string; // also unit of DRI values
    dris: DietaryReferenceIntake[];
}

export class DietaryReferenceIntake {
    sex: SexEnum;
    minAge: number;
    maxAge: number;
    // recommended daily allowance / adequate intake
    rdaai: number;
    // tollerable upper limit intake level
    tulil: number;
}

/**
 * https://www.nap.edu/read/13050/chapter/24#1107
 */
export const NutrientMetadataList: NutrientMetaData[] = [
    {
        nutrient: 'VitaminA',
        displayName: 'Vitamin A',
        aliases: ['Vitamin A, IU'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 600, tulil: 1700 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 900, tulil: 2800 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 900, tulil: 3000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 900, tulil: 3000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 900, tulil: 3000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 900, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 600, tulil: 1700 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 700, tulil: 2800 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 700, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 700, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 700, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 700, tulil: 3000 },
        ]
    },
    {
        nutrient: 'VitaminC',
        displayName: 'Vitamin C',
        aliases: ['Vitamin C, total ascorbic acid'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 45, tulil: 1200 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 75, tulil: 1800 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 90, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 90, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 90, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 90, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 45, tulil: 1200 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 65, tulil: 1800 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 75, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 75, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 75, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 75, tulil: 2000 },
        ]
    },
    {
        nutrient: 'VitaminD',
        displayName: 'Vitamin D',
        aliases: ['Vitamin D (D2 + D3), International Units'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 20, tulil: 100 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 15, tulil: 100 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 20, tulil: 100 },
        ]
    },
    {
        nutrient: 'VitaminE',
        displayName: 'Vitamin E',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 11, tulil: 600 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 15, tulil: 800 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 11, tulil: 600 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 15, tulil: 800 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 15, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 15, tulil: 1000 },
        ]
    },
    {
        nutrient: 'VitaminK',
        displayName: 'Vitamin K',
        aliases: [],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 60, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 75, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 120, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 120, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 120, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 120, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 60, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 75, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 90, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 90, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 90, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 90, tulil: null },
        ]
    },
    {
        nutrient: 'Thiamin',
        displayName: 'Thiamin',
        aliases: ['Thiamin'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 0.9, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1.2, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 1.2, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 1.2, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 1.2, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1.2, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 0.9, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.1, tulil: null },
        ]
    },
    {
        nutrient: 'Riboflavin',
        displayName: 'Riboflavin',
        aliases: ['Riboflavin'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 0.9, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1.3, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 1.3, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 1.3, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 1.3, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1.3, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 0.9, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.1, tulil: null },
        ]
    },
    {
        nutrient: 'Niacin',
        displayName: 'Niacin',
        aliases: ['Niacin'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 12, tulil: 20 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 16, tulil: 30 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 16, tulil: 35 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 16, tulil: 35 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 16, tulil: 35 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 16, tulil: 35 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 12, tulil: 20 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 14, tulil: 30 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 14, tulil: 35 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 14, tulil: 35 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 14, tulil: 35 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 14, tulil: 35 },
        ]
    },
    {
        nutrient: 'VitaminB6',
        displayName: 'Vitamin B-6',
        aliases: ['Vitamin B-6'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1, tulil: 60 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1.3, tulil: 80 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 1.3, tulil: 100 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 1.3, tulil: 100 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 1.7, tulil: 100 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1.7, tulil: 100 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1, tulil: 60 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1.2, tulil: 80 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1.3, tulil: 100 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1.3, tulil: 100 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1.5, tulil: 100 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.5, tulil: 100 },
        ]
    },
    {
        nutrient: 'Folate',
        displayName: 'Folate',
        aliases: ['Folate, total'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 300, tulil: 600 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 400, tulil: 800 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 300, tulil: 600 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 400, tulil: 800 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 400, tulil: 1000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 400, tulil: 1000 },
        ]
    },
    {
        nutrient: 'VitaminB12',
        displayName: 'Vitamin B-12',
        aliases: ['Vitamin B-12'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1.8, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1.8, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 2.4, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 2.4, tulil: null },
        ]
    },
    {
        nutrient: 'PantothenicAcid',
        displayName: 'Pantothenic Acid',
        aliases: ['Pantothenic acid'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 4, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 5, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 5, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 5, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 5, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 5, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 4, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 5, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 5, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 5, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 5, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 5, tulil: null },
        ]
    },
    {
        nutrient: 'Biotin',
        displayName: 'Biotin',
        aliases: [],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 20, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 25, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 30, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 30, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 30, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 30, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 20, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 25, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 30, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 30, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 30, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 30, tulil: null },
        ]
    },
    {
        nutrient: 'Choline',
        displayName: 'Choline',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 375, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 550, tulil: 3000 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 550, tulil: 3500 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 550, tulil: 3500 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 550, tulil: 3500 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 550, tulil: 3500 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 375, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 400, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 425, tulil: 3500 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 425, tulil: 3500 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 425, tulil: 3500 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 425, tulil: 3500 },
        ]
    },
    {
        nutrient: 'Boron',
        displayName: 'Boron',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: null, tulil: 11 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: null, tulil: 17 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: null, tulil: 20 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: null, tulil: 20 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: null, tulil: 20 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: null, tulil: 20 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: null, tulil: 11 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: null, tulil: 17 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: null, tulil: 20 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: null, tulil: 20 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: null, tulil: 20 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: null, tulil: 20 },
        ]
    },
    {
        nutrient: 'Calcium',
        displayName: 'Calcium',
        aliases: ['Calcium, Ca'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1300, tulil: 3000 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1300, tulil: 3000 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 1000, tulil: 2500 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 1000, tulil: 2500 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 1000, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1200, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1300, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1300, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1000, tulil: 2500 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1000, tulil: 2500 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1200, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1200, tulil: 2000 },
        ]
    },
    {
        nutrient: 'Chromium',
        displayName: 'Chromium',
        aliases: [],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 25, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 35, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 35, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 35, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 30, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 30, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 21, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 24, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 25, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 25, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 20, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 20, tulil: null },
        ]
    },
    {
        nutrient: 'Copper',
        displayName: 'Copper',
        aliases: ['Copper, Cu'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 700, tulil: 5000 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 890, tulil: 8000 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 700, tulil: 5000 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 890, tulil: 8000 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 900, tulil: 10000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 900, tulil: 10000 },
        ]
    },
    {
        nutrient: 'Fluoride',
        displayName: 'Fluoride',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 2, tulil: 10 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 3, tulil: 10 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 4, tulil: 10 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 4, tulil: 10 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 4, tulil: 10 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 4, tulil: 10 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 2, tulil: 10 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 3, tulil: 10 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 3, tulil: 10 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 3, tulil: 10 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 3, tulil: 10 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 3, tulil: 10 },
        ]
    },
    {
        nutrient: 'Iodine',
        displayName: 'Iodine',
        aliases: ['Iodine, I'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 120, tulil: 600 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 150, tulil: 900 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 120, tulil: 600 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 150, tulil: 900 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 150, tulil: 1100 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 150, tulil: 1100 },
        ]
    },
    {
        nutrient: 'Iron',
        displayName: 'Iron',
        aliases: ['Iron, Fe'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 8, tulil: 40 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 11, tulil: 45 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 8, tulil: 45 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 8, tulil: 45 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 8, tulil: 45 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 8, tulil: 45 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 8, tulil: 40 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 15, tulil: 45 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 18, tulil: 45 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 18, tulil: 45 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 8, tulil: 45 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 8, tulil: 45 },
        ]
    },
    {
        nutrient: 'Magnesium',
        displayName: 'Magnesium',
        aliases: ['Magnesium, Mg'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 240, tulil: 350 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 410, tulil: 350 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 400, tulil: 350 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 420, tulil: 350 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 420, tulil: 350 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 420, tulil: 350 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 240, tulil: 350 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 360, tulil: 350 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 310, tulil: 350 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 320, tulil: 350 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 320, tulil: 350 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 320, tulil: 350 },
        ]
    },
    {
        nutrient: 'Manganese',
        displayName: 'Manganese',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1.9, tulil: 6 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 2.2, tulil: 9 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 2.3, tulil: 11 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 2.3, tulil: 11 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 2.3, tulil: 11 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 2.3, tulil: 11 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1.6, tulil: 6 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1.6, tulil: 9 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1.8, tulil: 11 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1.8, tulil: 11 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1.8, tulil: 11 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.8, tulil: 11 },
        ]
    },
    {
        nutrient: 'Molybdenum',
        displayName: 'Molybdenum',
        aliases: [],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 34, tulil: 1100 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 43, tulil: 1700 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 34, tulil: 1100 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 43, tulil: 1700 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 45, tulil: 2000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 45, tulil: 2000 },
        ]
    },
    {
        nutrient: 'Nickel',
        displayName: 'Nickel',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: null, tulil: 0.6 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: null, tulil: 1 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: null, tulil: 1 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: null, tulil: 1 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: null, tulil: 1 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: null, tulil: 1 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: null, tulil: 0.6 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: null, tulil: 1 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: null, tulil: 1 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: null, tulil: 1 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: null, tulil: 1 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: null, tulil: 1 },
        ]
    },
    {
        nutrient: 'Phosphorus',
        displayName: 'Phosphorus',
        aliases: ['Phosphorus, P'],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1250, tulil: 4000 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1250, tulil: 4000 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 700, tulil: 4000 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 700, tulil: 4000 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 700, tulil: 4000 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 700, tulil: 3000 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1250, tulil: 4000 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1250, tulil: 4000 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 700, tulil: 4000 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 700, tulil: 4000 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 700, tulil: 4000 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 700, tulil: 3000 },
        ]
    },
    {
        nutrient: 'Selenium',
        displayName: 'Selenium',
        aliases: [],
        defaultUnit: 'mcg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 40, tulil: 280 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 40, tulil: 280 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 55, tulil: 400 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 55, tulil: 400 },
        ]
    },
    {
        nutrient: 'Vanadium',
        displayName: 'Vanadium',
        aliases: [],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: null, tulil: 1.8 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: null, tulil: 1.8 },
        ]
    },
    {
        nutrient: 'Zinc',
        displayName: 'Zinc',
        aliases: ['Zinc, Zn'],
        defaultUnit: 'mg',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 8, tulil: 23 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 11, tulil: 34 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 11, tulil: 40 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 11, tulil: 40 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 11, tulil: 40 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 11, tulil: 40 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 8, tulil: 23 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 9, tulil: 34 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 8, tulil: 40 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 8, tulil: 40 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 8, tulil: 40 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 8, tulil: 40 },
        ]
    },
    {
        nutrient: 'Potassium',
        displayName: 'Potassium',
        aliases: ['Potassium, K'],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 4.5, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 4.5, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 4.7, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 4.7, tulil: null },
        ]
    },
    {
        nutrient: 'Sodium',
        displayName: 'Sodium',
        aliases: ['Sodium, Na'],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1.5, tulil: 2.2 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1.5, tulil: 2.3 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 1.5, tulil: 2.3 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 1.5, tulil: 2.3 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 1.3, tulil: 2.3 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1.2, tulil: 2.3 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1.5, tulil: 2.2 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1.5, tulil: 2.3 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1.5, tulil: 2.3 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1.5, tulil: 2.3 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1.3, tulil: 2.3 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.2, tulil: 2.3 },
        ]
    },
    {
        nutrient: 'Chloride',
        displayName: 'Chloride',
        aliases: [],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 2.3, tulil: 3.4 },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 2.3, tulil: 3.6 },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 2.3, tulil: 3.6 },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 2.3, tulil: 3.6 },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 2, tulil: 3.6 },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1.8, tulil: 3.6 },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 2.3, tulil: 3.4 },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 2.3, tulil: 3.6 },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 2.3, tulil: 3.6 },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 2.3, tulil: 3.6 },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 2, tulil: 3.6 },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.8, tulil: 3.6 },
        ]
    },
    {
        nutrient: 'Carbohydrate',
        displayName: 'Carbohydrate',
        aliases: ['Carbohydrate, by difference', 'Carbohydrate, other'],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 130, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 130, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 130, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 130, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 130, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 130, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 130, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 130, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 130, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 130, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 130, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 130, tulil: null },
        ]
    },
    {
        nutrient: 'TotalFiber',
        displayName: 'Total Fiber',
        aliases: ['Fiber, total dietary'],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 31, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 38, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 38, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 38, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 30, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 30, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 26, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 26, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 25, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 25, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 21, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 21, tulil: null },
        ]
    },
    {
        nutrient: 'Fat',
        displayName: 'Fat',
        aliases: ['Total lipid (fat)'],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: null, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: null, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: null, tulil: null },
        ]
    },
    {
        nutrient: 'LinoleicAcid',
        displayName: 'Linoleic Acid',
        aliases: [],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 12, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 16, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 17, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 17, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 14, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 14, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 10, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 11, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 12, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 12, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 11, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 11, tulil: null },
        ]
    },
    {
        nutrient: 'AlphaLinolenicAcid',
        displayName: 'Alpha Linolenic Acid',
        aliases: [],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 1.2, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 1.6, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 1.6, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 1.6, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 1.6, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 1.6, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 1, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 1.1, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 1.1, tulil: null },
        ]
    },
    {
        nutrient: 'Protein',
        displayName: 'Protein',
        aliases: ['Protein'],
        defaultUnit: 'g',
        dris: [
            { sex: SexEnum.Male, minAge: 9, maxAge: 13, rdaai: 34, tulil: null },
            { sex: SexEnum.Male, minAge: 14, maxAge: 18, rdaai: 52, tulil: null },
            { sex: SexEnum.Male, minAge: 19, maxAge: 30, rdaai: 56, tulil: null },
            { sex: SexEnum.Male, minAge: 31, maxAge: 50, rdaai: 56, tulil: null },
            { sex: SexEnum.Male, minAge: 51, maxAge: 70, rdaai: 56, tulil: null },
            { sex: SexEnum.Male, minAge: 71, maxAge: null, rdaai: 56, tulil: null },
            { sex: SexEnum.Female, minAge: 9, maxAge: 13, rdaai: 34, tulil: null },
            { sex: SexEnum.Female, minAge: 14, maxAge: 18, rdaai: 46, tulil: null },
            { sex: SexEnum.Female, minAge: 19, maxAge: 30, rdaai: 46, tulil: null },
            { sex: SexEnum.Female, minAge: 31, maxAge: 50, rdaai: 46, tulil: null },
            { sex: SexEnum.Female, minAge: 51, maxAge: 70, rdaai: 46, tulil: null },
            { sex: SexEnum.Female, minAge: 71, maxAge: null, rdaai: 46, tulil: null },
        ]
    },
    {
        nutrient: 'Energy',
        displayName: 'Energy',
        aliases: ['Energy'],
        defaultUnit: 'kcal',
        dris: null
    },
    {
        nutrient: 'Cholesterol',
        displayName: 'Cholesterol',
        aliases: ['Cholesterol'],
        defaultUnit: 'mg',
        dris: null
    },
    {
        nutrient: 'TransFat',
        displayName: 'Trans Fat',
        aliases: ['Fatty acids, total trans'],
        defaultUnit: 'mg',
        dris: null
    },
    {
        nutrient: 'SaturatedFat',
        displayName: 'Saturated Fat',
        aliases: ['Fatty acids, total saturated'],
        defaultUnit: 'mg',
        dris: null
    },
    {
        nutrient: 'MonounsaturatedFat',
        displayName: 'Monounsaturated Fat',
        aliases: ['Fatty acids, total monounsaturated'],
        defaultUnit: 'mg',
        dris: null
    },
    {
        nutrient: 'PolyunsaturatedFat',
        displayName: 'Polyunsaturated Fat',
        aliases: ['Fatty acids, total polyunsaturated'],
        defaultUnit: 'mg',
        dris: null
    }

];
